# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "WQrSe0KUGrygqpDjcYl/kTgVupaWEaUvKheN4ldhAYozm27A/LrHgmrUQoKvwKDianzUDSCuZkIMc4jzxPzbUL+Fo1gbgr+xRwGUUcvSj85YqFagDk5gwrl3VkQmyixZCL5u4FvzV0TDn/pTk6dViCaGU24ejm05ZKxsu6ddN4tqng1+QeGHIuV0WOU1ZZ65x7rEUltuCwVigITg6yq0fQnv+awq/5jCr+QEicP0+0wdwQcMU7ya+ycx80ywo7oUwPP0PL2XD6UaCSYbAYXYWXoE53UmF6uB4eCKktDN0apIi8tHF1laClboWlU7JhjNxP5gaWw1caRJ4ThpXKpM+qlCMVVpFbnavtnxtoXtuyXosUd79rf8/mFrDbh/hkPTmhWsp14t2hwnQ3mg8HpCUkRRMh9Kdgyk+4ajBPXZnM1rF9uZzDJuF0Ir0WV72i67p0mTQZmqbycHAxgkXZI2JWbGH6lEZva2Z2Xh1I+gJeQsrv3x/TtwENRLZULrrSRJKSpJTlcqI9PYe9/JdM5qecBSSQXZaqI+ntjuTMpiEa5S8tbaQELTIov+cCg54E87aQps5X55kSO+2vt8AOW3RqF5nhRlCzEqaFFRAKW7+P6kVajfT0nacBMnXRUhjZpQoPZqkIcenSitRGHt/deitBxpPS5ZLnDA0h9vuEn4QI0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
