travis:
  secure:
    BINSTAR_TOKEN: T9W0YzXLCmuRTnxEOGewaXP/aGqcFJxtsUdCCbfeo5JMHFYex987/WzvgxqitUgC9/gg5MRv8dphnwqOrepgU6V4E1/MWM5e1wzGDSVjq0YWfHkYHWJXnF6rylD45Zt4gl1KvogwidCnCI3isHu0r45ONGjpOpSDhSWMjLDNCKjWYnWycTJjrprSfNHaVQYO7QiuBfTr1A1oEoZSvi/iIZcLORbPlV7/ea8zNrOz5wwpWhLEeJjeU4++DBo/Y08BDliZGzNmKUahaNAslpqS+x77xwOSRsDIzmMFUKByjAB9CS56pE1rD7JiBq4gUrMJIuFXFB+PVADiok6l7RHQt8+RaOZhvYcySTsbbdV655G/CSHe3NVcJ6IHz92QzoB4zAIA+b1MWdhFoO5o39xO70MmHIS4aRECYS+9HS4MMI4/Pxuz5oXNhZ8oCJNi5mITo8wrmPtaNjVKvpBP7LgcQwZF6ghqn+B8JNgwAY5UI/IKk0wM6cbNtVXwjYQpj5YKjI7rBgYZaRmmdBWTfTxRrVBGY6lMQjliuqgTlBSz5HBLzApbB9N6wCM6NF5ShpvZYMn5qeWuWttN/Q3kS7k/blh+gSeoCTeENDsQc+7NfnDvcskOOq95yJ5wueS7xTllox/BCuplVajU/0fZVMgx8Xtm91ohuzvyp5uThoFSV5U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
